#server
server:
  port: 8086

#spring
spring:
  application:
    name: market-server

  http:
    encoding:
      charset: utf-8

  eureka:
    client:
      register-with-eureka: true  # 服务注册，false表示不将自已注册到Eureka服务中
      fetch-registry: true  # 服务发现，false表示自己不从Eureka服务中获取注册信息
      service-url: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址, 单机版配 置自己（如果不配置则默认本机8761端口）
        defaultZone: http://localhost:8761/eureka/

    instance:
      instance-id: ${spring.application.name}:${server.port} #指定实例ID,就不会显示主机名了 prefer-ip-address: true #访问路径可以显示IP地址
      prefer-ip-address: true #访问路径可以显示IP地址


# 在Feign中需要开启 Hystrix
feign:
  hystrix:
    enabled: true

#  在被监控服务上添加暴露端点 - hystrix
management:
    endpoints:
       web:
         exposure:
           include: hystrix.stream
