server:
  port: 7001

spring:
  application:
    name: zull_server
eureka:
  client:
    register-with-eureka: true # 服务注册，false表示不将自已注册到Eureka服务中
    fetch-registry: true   # 服务发现 ，false表示自己不从Eureka服务中获取注册信息
    service-url: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址, 单机版配 置自己（如果不配置则默认本机8761端口）
       defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port} #指定实例ID,就不会显示主机名了 prefer-ip-address: true #访问路径可以显示IP地址
    prefer-ip-address: true #访问路径可以显示IP地址

zuul:
  routes:
    povider-product: # 路由名称，名称任意，保持所有路由名称唯一
      path: /base/** # 访问路径
      serviceId: base-server # 指定服务ID，会自动从Eureka中找到此服务的ip和端 口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时 请求 /product/get/1，代理转发到/get/1

    # 如果多个服务需要经过路由，则同povider-product方式继续添加，例如：
    #provider-order:
      #path: /order/**
      #serviceId: microservice-order
      #stripPrefix: false