server:
  port: 8762 # eureka 默认端口

eureka:
  instance:
    hostname: eureka_two # 配置eureka 服务名

  server:
    enable-self-preservation: false #关闭自我保护机制

  client:
    register-with-eureka: false  # 服务注册，false表示不将自已注册到Eureka服务中
    fetch-registry: false  # 服务发现，false表示自己不从Eureka服务中获取注册信息
    service-url: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址, 单机版配 置自己（如果不配置则默认本机8761端口）
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
