# 端口号
server:
  port: 8089

spring:
  application:
    name: spring_boot_dome

  # 数据库链接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/spring_cloud_database?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: mysql

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
  # password: 没有密码可以不用填写

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boot.demo.pojo

# 使用日志来记录
logging:
  level:
    com.boot.demo.mapper: debug
  path: D:/logs/