server:
  port: 8088

spring:
  application:
    name: spring_boot_dome

  # 数据库链接
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1/spring_cloud_database?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: mysql

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boot.demo.pojo

#  系统日志 使用 springboot原生
logging:
  level:
    org.
    com.boot.demo.mapper : debug
    path: D:/logs/