server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring_boot_dome

  # 数据库链接
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1/spring_cloud_database?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: mysql

  #redis
  redis:
    database: 0 # Redis数据库索引（默认为0）
    timeout: 3000 # 连接超时时间（毫秒）
    host: 127.0.0.1
    port: 6379 # 端口号
    password: # 没有密码可以不用填写
    lettuce:
      pool:
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 1  # 连接池中的最小空闲连接
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boot.demo.pojo

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug