server:
  port: 8999

spring:
  application:
    name: spring_boot_dome

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 所在xml 位置
  type-aliases-package: com.boot.demo.pojo  # 所在实体类 位置